### PR TITLE
add source distribution step to workflow

### PR DESCRIPTION
**Pull request by abrammer**
Add source distribution to wheelhouse directory for artifact and pypi upload.   Follow on from #49.  

Note, I think this will work, but don't have experience actually doing this specific step for upload to pypi.  Might be worth pushing an alpha release branch just to test this whole workflow.  A branch with the version `0.10.3a1` or similar pre-release version number with a tag should get uploaded to test.pypi without doing anything to master or real pypi.

### CODE REVIEW

**Comment by fhs** [comment]
It failed: https://github.com/fhs/pyhdf/runs/2605865798

**Comment by abrammer** [comment]
Ahh, not the error I expected but makes sense.  Added the numpy dep and bumped the setup.py version so the upload doesn't collide with any 10.2 versions already uploaded.  Ran a test workflow in my repo and other than an obvious pypi authentication issue, looks like everything should be right now.  Both wheels and the tar.gz were ready to be uploaded.

**Comment by fhs** [comment]
@abrammer The alpha seems to be working now. I had to install numpy manually in a fresh virtualenv before I could import `pyhdf.SD`. I wonder why numpy isn't being installed automatically by pip when I install pyhdf. There is a `pyproject.toml` which lists build dependencies. Do we need something else for wheels? `requirements.txt`?

**Comment by abrammer** [comment]
Awesome, yeah I see the wheels on test pypi and a pip install works.  For the numpy issue, I think I know the answer.  the `pyproject.toml` setups the build environment but installing through a wheel isn't a build anymore.   This can be defined in `setup.cfg` d78cff8 which based on another of my repos should solve that

**Review by fhs — APPROVED** [review]
So, with alpha3, it tries to *build* numpy because test.pypi.org doesn't have the binaries. The build fails for me probably because the numpy version on test.pypi.org is really old.

I think it'll work once I push to the main pypi.org site. Great work!

**Comment by abrammer** [comment]
Awesome, yeah would think the same about it pulling from the same pypi url.  Just make sure to update the `setup.py` version on the "release" commit.  The wheels and tar file are named based on that version not the git tag.  But I think that's the same as it would have been for your previous releases.

**Comment by fhs** [comment]
It worked. :tada:

**Pull request merged**
